on:
  release:
    types: [released]
name: Nuget package on new release
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Push
      run: dotnet nuget push ".\Nuget\*.symbols.nupkg" --skip-duplicate --api-key {{ secrets.GIAMMINLIBNUGETKEY }} --source https://api.nuget.org/v3/index.json
